name: CI/CD Pipeline bedrock

on:
  push:
    branches:
      - main

jobs:
  dockerize-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Bandit Security Scan
        run: |
          pip install bandit -r requirements.txt
          bandit src/apiserver.py -f html -o bandit-report-backend.html || true

      - name: Upload Bandit Report
        uses: actions/upload-artifact@v4
        with:
          name: bandit-report-backend
          path: bandit-report-backend.html

      - name: Run pip-audit for dependency vulnerabilities
        run: |
          pip install pip-audit
          pip-audit -r src/requirements.txt -f json -o pip-audit-report.json || true

      - name: Upload SCA Report
        uses: actions/upload-artifact@v4
        with:
          name: pip-audit-report-backend
          path: pip-audit-report.json

      - name: Set up Docker image tag
        id: vars
        run: echo "TAG=${{ github.sha }}" >> $GITHUB_ENV

      - name: Build docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/code-analyzer-backend:${{ env.TAG }} .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/code-analyzer-backend:${{ env.TAG }}